---
name: rewrite-with-folds
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  rewrite-with-folds-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [rewrite-with-folds, hspec]
