---
name: zipping-exercises
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  zipping-exercises-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [zipping-exercises, hspec]
