---
name: funcs
dependencies: base >= 4.7 && < 5
library: {source-dirs: src}
tests:
  funcs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [funcs, hspec]
