---
name: small-library-for-maybe
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  small-library-for-maybe-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [small-library-for-maybe, hspec]
