---
name: eft
dependencies: base >= 4.7 && < 5
library: {source-dirs: src}
tests:
  eft-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [eft, hspec, QuickCheck]
...
