---
name: wordnumber
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
  ghc-options: [-Wall, -Werror]
tests:
  wordnumber-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [hspec, wordnumber]
...
