---
name: unfolds
dependencies: base >= 4.7 && < 5
ghc-options: -Wall -Wno-type-defaults
library:
  source-dirs: src
tests:
  unfolds-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [unfolds, hspec]
