---
name: db-processing
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  db-processing-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [db-processing, hspec]
