---
name: sum-monad
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  sum-monad-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [sum-monad, hspec]
