---
name: small-library-for-either
dependencies: base >= 4.7 && < 5
ghc-options: -Wall -Wno-type-defaults
library:
  source-dirs: src
tests:
  small-library-for-either-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [small-library-for-either, hspec]
