---
name: multiply
description: "8.6.3 Recursion, exercise 3"
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  multiply-to-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [multiply, hspec]
...
