---
name: string-processing
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  string-processing-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [string-processing, hspec]
