---
name: write-your-own-iterate-and-unfoldr
dependencies: base >= 4.7 && < 5
ghc-options: -Wall -Wno-type-defaults
library:
  source-dirs: src
tests:
  write-your-own-iterate-and-unfoldr-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [write-your-own-iterate-and-unfoldr, hspec]
