---
name: stop-vowel-stop
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  stop-vowel-stop-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [stop-vowel-stop, hspec]
