---
name: data-char
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  data-char-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [data-char, hspec]
