---
name: instances
description: A test suite for the Applicative type class laws.

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - checkers

library:
  source-dirs: src

tests:
  instances-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [instances, QuickCheck, checkers]
