---
name: comprehend-thy-lists
dependencies: base >= 4.7 && < 5
library: {source-dirs: src}
tests:
  comprehend-thy-lists-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [comprehend-thy-lists, hspec]
...
