---
name: library-functions
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  library-functions-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
      -fno-max-valid-hole-fits
    dependencies: [library-functions, hspec]
