---
name:                palindrom-testing
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  palindrom-testing-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [palindrom-testing, hspec, QuickCheck]
