---
name: thy-fearful-symmetry
dependencies: base >= 4.7 && < 5
library: {source-dirs: src}
tests:
  thy-fearful-symmetry-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [thy-fearful-symmetry, hspec, QuickCheck]
...
