-- 11.3 Data and type constructors, page 391
--
--
data Trivial = Trivial'
--     [1]       [2]
--
--  1. Trivial is like a constant value but at the type level. It takes no
--     arguments and thus is nullary. The Haskell Report calls these type
--     constants to distinguish them from type constructors that take arguments.
--  2. The data constructor Trivial' is also like a constant value but it
--     exists in value, term, or runtime space. These are not three different
--     things but three names for the sasme space that types serve to describe.
--
data UnaryTypeCon a = UnaryValueCon a
--        [3]              [4]
--
--  3. UnaryTyepCon is a type constructor of one argument. It's a constructor
--     awaiting a type constant to be applied to, but it has non behavior in
--     the sense that we think of functions as having. Such type-level functions
--     exist but are not covered in this book.
--  4. UnaryValueCon is a data constructor of one argument awaiting a value to be
--     applied to. Again, it doesn't behave like a term-level function in the sense
--     of performing an operation on data. It's more like a box to put values into.
--     Be careful with the box/container analogy as it will betray you later -- not
--     all type arguments to constructors have value-level witnesses! Some are
--     phantom.
