---
name: optional-monoid
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  optional-monoid-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [optional-monoid, hspec, QuickCheck]
