---
name: square-cube
dependencies: base >= 4.7 && < 5
library: {source-dirs: src}
tests:
  square-cube-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [square-cube, hspec]
