---
name: write-the-instances
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  write-the-instances-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [write-the-instances, hspec, QuickCheck]
