---
name: functor-instances
dependencies: base >= 4.7 && < 5
library: {source-dirs: src}
tests:
  functor-instances-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [functor-instances, hspec, QuickCheck]
