---
name: logicgoats
dependencies: base >= 4.7 && < 5
library: {source-dirs: src}
tests:
  logicgoats-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: {-threaded, -rtsopts, -with-rtsopts=-N}
    dependencies: [logicgoats, hspec]
