---
name: mult
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  mult-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [mult, hspec, QuickCheck]
