---
name: semigroup-exercises
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
  exposed-modules: Lib
  dependencies: [QuickCheck]
tests:
  semigroup-exercises-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [semigroup-exercises, hspec, QuickCheck]
