-- 11.2 Data declarations review, page 388
--
-- page 389
{--}data Bool  =  False   |   True
--   [1]  [2] [3]   [4]  [5]   [6]
--
--   1. Keyword to signal what follows it a data declaratation.
--   2. Type constructor (with no arguments).
--   3. Equals sign divides the type constructor from its data constructors.
--   5. The pipe denotes a sum type which indicates a logical disjunction
--      (colloquially, "or") in what values can have that type.
--
{--}data [] a   =  []  |  a : [a]
--       [ 7 ]     [8]     [9]
--
--   7. Type constructor with an argument. An empty list has to be applied
--      to an argument in order to become a list of something. Here the
--      argument is a polymorphic type variable, so the list's argument
--      can be of different types.
--   8. Data constructor for the empty list.
--   9. Data constructor that takes two arguments: an a and also a [a].
