---
name: warming-up
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  warming-up-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [warming-up, hspec]
