---
name: dodgy
dependencies: base >= 4.7 && < 5
library:
  source-dirs: src
tests:
  dodgy-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [dodgy, hspec]
...
