---
name: lookups
dependencies: base >= 4.7 && < 5
library: {source-dirs: src}
tests:
  lookups-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [lookups, hspec, QuickCheck]
