---
name: binary-tree
dependencies: base
library:
  source-dirs: src
tests:
  binary-tree-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies: [binary-tree, hspec]
